# Generated by Django 5.2.4 on 2025-08-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email is required.', 'required': 'Please provide your email address.'}, max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
